services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    access_control_manager:
        class: \PoP\AccessControl\Services\AccessControlManager
        public: true

    PoP\AccessControl\Hooks\:
        resource: '../src/Hooks/*'
        public: true
