services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\AccessControl\Conditional\CacheControl\Hooks\:
        resource: '../../../src/Conditional/CacheControl/Hooks/*'
        public: true
